services:
  - type: web
    name: mafia-fantasy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: DATABASE_URL
        value: sqlite:///instance/mafia_fantasy.db
      - key: UPLOAD_FOLDER
        value: /var/lib/render/instance
      - key: SECRET_KEY
        generateValue: true