"""Add country_code field to Card model

Revision ID: 42f3f2cd6d0d
Revises: 5b9265a0eb8b
Create Date: 2025-06-27 18:12:00.765581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f3f2cd6d0d'
down_revision = '5b9265a0eb8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_code', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('country_code')

    # ### end Alembic commands ###
